[profile.default]
test-threads = 4
retries = 2
slow-timeout = { period = "60s", terminate-after = 2 }
leak-timeout = "10s"
fail-fast = false
timeout = "300s"

[profile.ci]
inherits = "default"
test-threads = 1
retries = 3
slow-timeout = { period = "120s", terminate-after = 1 }
leak-timeout = "30s"
fail-fast = true

[profile.performance]
inherits = "default"
test-threads = 1
retries = 1
slow-timeout = { period = "300s", terminate-after = 1 }
leak-timeout = "60s"
fail-fast = false