[package]
name = "leptos-shadcn-progress"
description = "Leptos port of shadcn/ui progress"
homepage = "https://shadcn-ui.rustforweb.org/components/progress.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.7.0"

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
leptos-struct-component.workspace = true
leptos-style.workspace = true
tailwind_fuse.workspace = true
web-sys.workspace = true
leptos-shadcn-signal-management = { path = "../../signal-management" }

[features]
default = []
new_york = []

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }
