[package]
name = "standalone-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
# Leptos framework
leptos = { version = "0.8", features = ["csr"] }

# WASM-compatible dependencies
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"
getrandom = { version = "0.2", features = ["js"] }

# Tailwind-RS v0.4.0 (Latest WASM-compatible versions)
tailwind-rs-core = "0.4.0"
tailwind-rs-wasm = "0.4.0"

# UUID support for WASM
uuid = { version = "1.0", features = ["v4", "js"] }

# Binary target
[[bin]]
name = "standalone-demo"
path = "src/main.rs"
