# Trunk configuration for Leptos ShadCN UI Demo
[build]
target = "index.html"
dist = "dist"
public_url = "/"

[serve]
port = 8080
open = false
watch = true

[clean]
dist = "dist"
cargo = false

# Workspace configuration
[workspace]
root = "."
