- name: 'type: bug'
  description: 'Bug'
  color: '3e63dd'
- name: 'type: documentation'
  description: 'Documentation'
  color: '3e63dd'
- name: 'type: feature'
  description: 'Feature'
  color: '3e63dd'
- name: 'type: maintenance'
  description: 'Maintenance'
  color: '3e63dd'
- name: 'type: question'
  description: 'Question'
  color: '3e63dd'

- name: 'framework: dioxus'
  description: 'Dioxus'
  color: 'd6409f'
- name: 'framework: leptos'
  description: 'Leptos'
  color: 'd6409f'
- name: 'framework: yew'
  color: 'd6409f'
  description: 'Yew'

- name: 'component: accordion'
  description: 'Accordion'
  color: 'ffc53d'
- name: 'component: alert'
  description: 'Alert'
  color: 'ffc53d'
- name: 'component: alert dialog'
  description: 'Alert Dialog'
  color: 'ffc53d'
- name: 'component: aspect ratio'
  description: 'Aspect Ratio'
  color: 'ffc53d'
- name: 'component: avatar'
  description: 'Avatar'
  color: 'ffc53d'
- name: 'component: badge'
  description: 'Badge'
  color: 'ffc53d'
- name: 'component: breadcrumb'
  description: 'Breadcrumb'
  color: 'ffc53d'
- name: 'component: button'
  description: 'Button'
  color: 'ffc53d'
- name: 'component: calendar'
  description: 'Calendar'
  color: 'ffc53d'
- name: 'component: card'
  description: 'Card'
  color: 'ffc53d'
- name: 'component: carousel'
  description: 'Carousel'
  color: 'ffc53d'
- name: 'component: chart'
  description: 'Chart'
  color: 'ffc53d'
- name: 'component: checkbox'
  description: 'Checkbox'
  color: 'ffc53d'
- name: 'component: collapsible'
  description: 'Collapsible'
  color: 'ffc53d'
- name: 'component: combobox'
  description: 'Combobox'
  color: 'ffc53d'
- name: 'component: command'
  description: 'Command'
  color: 'ffc53d'
- name: 'component: context menu'
  description: 'Context Menu'
  color: 'ffc53d'
- name: 'component: data table'
  description: 'Data Table'
  color: 'ffc53d'
- name: 'component: date picker'
  description: 'Date Picker'
  color: 'ffc53d'
- name: 'component: dialog'
  description: 'Dialog'
  color: 'ffc53d'
- name: 'component: drawer'
  description: 'Drawer'
  color: 'ffc53d'
- name: 'component: dropdown menu'
  description: 'Dropdown Menu'
  color: 'ffc53d'
- name: 'component: form'
  description: 'Form'
  color: 'ffc53d'
- name: 'component: hover card'
  description: 'Hover Card'
  color: 'ffc53d'
- name: 'component: input'
  description: 'Input'
  color: 'ffc53d'
- name: 'component: input otp'
  description: 'Input OTP'
  color: 'ffc53d'
- name: 'component: label'
  description: 'Label'
  color: 'ffc53d'
- name: 'component: menubar'
  description: 'Menubar'
  color: 'ffc53d'
- name: 'component: navigation menu'
  description: 'Navigation Menu'
  color: 'ffc53d'
- name: 'component: pagination'
  description: 'Pagination'
  color: 'ffc53d'
- name: 'component: popover'
  description: 'Popover'
  color: 'ffc53d'
- name: 'component: progress'
  description: 'Progress'
  color: 'ffc53d'
- name: 'component: radio group'
  description: 'Radio Group'
  color: 'ffc53d'
- name: 'component: resizable'
  description: 'Resizable'
  color: 'ffc53d'
- name: 'component: scroll area'
  description: 'Scroll Area'
  color: 'ffc53d'
- name: 'component: select'
  description: 'Select'
  color: 'ffc53d'
- name: 'component: separator'
  description: 'Separator'
  color: 'ffc53d'
- name: 'component: sheet'
  description: 'Sheet'
  color: 'ffc53d'
- name: 'component: skeleton'
  description: 'Skeleton'
  color: 'ffc53d'
- name: 'component: slider'
  description: 'Slider'
  color: 'ffc53d'
- name: 'component: sonner'
  description: 'Sonner'
  color: 'ffc53d'
- name: 'component: switch'
  description: 'Switch'
  color: 'ffc53d'
- name: 'component: table'
  description: 'Table'
  color: 'ffc53d'
- name: 'component: tabs'
  description: 'Tabs'
  color: 'ffc53d'
- name: 'component: textarea'
  description: 'Textarea'
  color: 'ffc53d'
- name: 'component: toast'
  description: 'Toast'
  color: 'ffc53d'
- name: 'component: toggle'
  description: 'Toggle'
  color: 'ffc53d'
- name: 'component: toggle group'
  description: 'Toggle Group'
  color: 'ffc53d'
- name: 'component: tooltip'
  description: 'Tooltip'
  color: 'ffc53d'
