[package]
name = "leptos-shadcn-avatar"
description = "Leptos port of shadcn/ui avatar"
homepage = "https://shadcn-ui.rustforweb.org/components/avatar.html"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.3.0"
publish = true

[dependencies]
leptos = { workspace = true }
leptos-style = { workspace = true }
tailwind_fuse = { workspace = true }
web-sys = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
