[package]
name = "leptos-shadcn-lazy-loading"
description = "Lazy loading system for shadcn/ui Leptos components"
homepage = "https://shadcn-ui.rustforweb.org/components/lazy-loading.html"

[dependencies]
leptos.workspace = true

[dev-dependencies]
leptos = { workspace = true, features = ["csr"] }
