[package]
name = "leptos-shadcn-combobox"
description = "Leptos port of shadcn/ui Combobox component"
homepage = "https://shadcn-ui.rustforweb.org/components/combobox.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.7.0"

[dependencies]
leptos.workspace = true
leptos-style = "0.2"
web-sys = { version = "0.3", features = ["HtmlInputElement", "HtmlElement", "Element", "Node", "NodeList", "Event", "EventTarget", "MouseEvent", "KeyboardEvent", "FocusEvent"] }
wasm-bindgen = "0.2"
tailwind_fuse = "0.1"
gloo-timers = "0.3"
leptos-struct-component = "0.2"

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }

[lib]
name = "leptos_shadcn_combobox"
path = "src/lib.rs"

[[example]]
name = "combobox_example"
path = "examples/combobox_example.rs"
