[package]
name = "leptos-shadcn-command"
description = "Leptos port of shadcn/ui command"
homepage = "https://shadcn-ui.rustforweb.org/components/command.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.7.0"

[dependencies]
leptos = { workspace = true, features = ["csr", "ssr"] }
tailwind_fuse.workspace = true
serde = { version = "1.0", features = ["derive"] }
web-sys = "0.3"

[features]
default = ["leptos/csr"]
csr = ["leptos/csr"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]
new_york = []

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }
