[package]
name = "leptos-shadcn-ui"
version = "0.2.0"
edition = "2021"
description = "A comprehensive collection of beautiful, accessible UI components built for Leptos v0.8+, inspired by shadcn/ui. Modern Rust implementation with 100% test coverage, automated testing infrastructure, and production-ready quality standards."
homepage = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
repository = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
license = "MIT"
authors = ["CloudShuttle <info@cloudshuttle.com>"]
keywords = ["leptos", "ui", "components", "shadcn", "web", "rust", "wasm", "modern"]
categories = ["wasm", "gui", "web-programming"]
readme = "../../README.md"
rust-version = "1.70"

[dependencies]
# Core Leptos dependencies (v0.8.x)
leptos = "0.8"
leptos_router = "0.8"
leptos-node-ref = "0.2"
leptos-struct-component = "0.2"
leptos-style = "0.2"

# Individual component packages (workspace dependencies for v0.2.0 release)
leptos-shadcn-button = { path = "../leptos/button", optional = true }
leptos-shadcn-input = { path = "../leptos/input", optional = true }
leptos-shadcn-label = { path = "../leptos/label", optional = true }
leptos-shadcn-checkbox = { path = "../leptos/checkbox", optional = true }
leptos-shadcn-switch = { path = "../leptos/switch", optional = true }
leptos-shadcn-radio-group = { path = "../leptos/radio-group", optional = true }
leptos-shadcn-select = { path = "../leptos/select", optional = true }
leptos-shadcn-textarea = { path = "../leptos/textarea", optional = true }
leptos-shadcn-card = { path = "../leptos/card", optional = true }
leptos-shadcn-separator = { path = "../leptos/separator", optional = true }
leptos-shadcn-tabs = { path = "../leptos/tabs", optional = true }
leptos-shadcn-accordion = { path = "../leptos/accordion", optional = true }
leptos-shadcn-dialog = { path = "../leptos/dialog", optional = true }
leptos-shadcn-popover = { path = "../leptos/popover", optional = true }
leptos-shadcn-tooltip = { path = "../leptos/tooltip", optional = true }
leptos-shadcn-alert = { path = "../leptos/alert", optional = true }
leptos-shadcn-badge = { path = "../leptos/badge", optional = true }
leptos-shadcn-skeleton = { path = "../leptos/skeleton", optional = true }
leptos-shadcn-progress = { path = "../leptos/progress", optional = true }
leptos-shadcn-toast = { path = "../leptos/toast", optional = true }
leptos-shadcn-table = { path = "../leptos/table", optional = true }
leptos-shadcn-calendar = { path = "../leptos/calendar", optional = true }
leptos-shadcn-date-picker = { path = "../leptos/date-picker", optional = true }
leptos-shadcn-pagination = { path = "../leptos/pagination", optional = true }
leptos-shadcn-slider = { path = "../leptos/slider", optional = true }
leptos-shadcn-toggle = { path = "../leptos/toggle", optional = true }
leptos-shadcn-carousel = { path = "../leptos/carousel", optional = true }

# Advanced components (workspace dependencies for v0.2.0 release)
leptos-shadcn-form = { path = "../leptos/form", optional = true }
leptos-shadcn-combobox = { path = "../leptos/combobox", optional = true }
leptos-shadcn-command = { path = "../leptos/command", optional = true }
leptos-shadcn-input-otp = { path = "../leptos/input-otp", optional = true }
leptos-shadcn-breadcrumb = { path = "../leptos/breadcrumb", optional = true }
leptos-shadcn-navigation-menu = { path = "../leptos/navigation-menu", optional = true }
leptos-shadcn-context-menu = { path = "../leptos/context-menu", optional = true }
leptos-shadcn-dropdown-menu = { path = "../leptos/dropdown-menu", optional = true }
leptos-shadcn-menubar = { path = "../leptos/menubar", optional = true }
leptos-shadcn-hover-card = { path = "../leptos/hover-card", optional = true }
leptos-shadcn-aspect-ratio = { path = "../leptos/aspect-ratio", optional = true }
leptos-shadcn-collapsible = { path = "../leptos/collapsible", optional = true }
leptos-shadcn-scroll-area = { path = "../leptos/scroll-area", optional = true }
leptos-shadcn-sheet = { path = "../leptos/sheet", optional = true }
leptos-shadcn-drawer = { path = "../leptos/drawer", optional = true }
leptos-shadcn-alert-dialog = { path = "../leptos/alert-dialog", optional = true }
leptos-shadcn-avatar = { path = "../leptos/avatar", optional = true }

# Additional dependencies
tailwind_fuse = "0.3"
lucide-leptos.workspace = true
gloo-timers = "0.3"

[features]
default = ["all-components"]
all-components = [
    "button", "input", "label", "checkbox", "switch", "radio-group", "select", "textarea",
    "card", "separator", "tabs", "accordion", "dialog", "popover", "tooltip",
    "alert", "badge", "skeleton", "progress", "toast", "table", "calendar", "date-picker", "pagination",
    "slider", "toggle", "carousel",
    "form", "combobox", "command", "input-otp", "breadcrumb", "navigation-menu", "context-menu", 
    "dropdown-menu", "menubar", "hover-card", "aspect-ratio", "collapsible", "scroll-area", 
    "sheet", "drawer", "alert-dialog", "avatar"
]

# Individual component features
button = ["leptos-shadcn-button"]
input = ["leptos-shadcn-input"]
label = ["leptos-shadcn-label"]
checkbox = ["leptos-shadcn-checkbox"]
switch = ["leptos-shadcn-switch"]
radio-group = ["leptos-shadcn-radio-group"]
select = ["leptos-shadcn-select"]
textarea = ["leptos-shadcn-textarea"]
card = ["leptos-shadcn-card"]
separator = ["leptos-shadcn-separator"]
tabs = ["leptos-shadcn-tabs"]
accordion = ["leptos-shadcn-accordion"]
dialog = ["leptos-shadcn-dialog"]
popover = ["leptos-shadcn-popover"]
tooltip = ["leptos-shadcn-tooltip"]
alert = ["leptos-shadcn-alert"]
badge = ["leptos-shadcn-badge"]
skeleton = ["leptos-shadcn-skeleton"]
progress = ["leptos-shadcn-progress"]
toast = ["leptos-shadcn-toast"]
table = ["leptos-shadcn-table"]
calendar = ["leptos-shadcn-calendar"]
date-picker = ["leptos-shadcn-date-picker"]
pagination = ["leptos-shadcn-pagination"]
slider = ["leptos-shadcn-slider"]
toggle = ["leptos-shadcn-toggle"]
carousel = ["leptos-shadcn-carousel"]
form = ["leptos-shadcn-form"]
combobox = ["leptos-shadcn-combobox"]
command = ["leptos-shadcn-command"]
input-otp = ["leptos-shadcn-input-otp"]
breadcrumb = ["leptos-shadcn-breadcrumb"]
navigation-menu = ["leptos-shadcn-navigation-menu"]
context-menu = ["leptos-shadcn-context-menu"]
dropdown-menu = ["leptos-shadcn-dropdown-menu"]
menubar = ["leptos-shadcn-menubar"]
hover-card = ["leptos-shadcn-hover-card"]
aspect-ratio = ["leptos-shadcn-aspect-ratio"]
collapsible = ["leptos-shadcn-collapsible"]
scroll-area = ["leptos-shadcn-scroll-area"]
sheet = ["leptos-shadcn-sheet"]
drawer = ["leptos-shadcn-drawer"]
alert-dialog = ["leptos-shadcn-alert-dialog"]
avatar = ["leptos-shadcn-avatar"]

# Modern Rust features
modern-rust = []
leptos-v0-8 = []
wasm-optimized = []
quality-assured = []

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[package.metadata.playground]
components = ["button", "card", "input", "dialog"]
