[package]
name = "leptos-shadcn-ui"
version = "0.1.0"
edition = "2021"
description = "A comprehensive collection of beautiful, accessible UI components built for Leptos v0.8+, inspired by shadcn/ui"
homepage = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
repository = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
license = "MIT"
authors = ["CloudShuttle <info@cloudshuttle.com>"]
keywords = ["leptos", "ui", "components", "shadcn", "web", "wasm", "rust"]
categories = ["wasm", "gui", "web-programming"]
readme = "README.md"

[dependencies]
# Core Leptos dependencies
leptos = "0.8"
leptos_router = "0.8"
leptos-node-ref = "0.2"
leptos-struct-component = "0.2"
leptos-style = "0.2"

# Individual component packages (workspace dependencies)
leptos-shadcn-button = { workspace = true, optional = true }
leptos-shadcn-input = { workspace = true, optional = true }
leptos-shadcn-label = { workspace = true, optional = true }
leptos-shadcn-checkbox = { workspace = true, optional = true }
leptos-shadcn-switch = { workspace = true, optional = true }
leptos-shadcn-radio-group = { workspace = true, optional = true }
leptos-shadcn-select = { workspace = true, optional = true }
leptos-shadcn-textarea = { workspace = true, optional = true }
leptos-shadcn-card = { workspace = true, optional = true }
leptos-shadcn-separator = { workspace = true, optional = true }
leptos-shadcn-tabs = { workspace = true, optional = true }
leptos-shadcn-accordion = { workspace = true, optional = true }
leptos-shadcn-dialog = { workspace = true, optional = true }
leptos-shadcn-popover = { workspace = true, optional = true }
leptos-shadcn-tooltip = { workspace = true, optional = true }
leptos-shadcn-alert = { workspace = true, optional = true }
leptos-shadcn-badge = { workspace = true, optional = true }
leptos-shadcn-skeleton = { workspace = true, optional = true }
leptos-shadcn-progress = { workspace = true, optional = true }
leptos-shadcn-toast = { workspace = true, optional = true }
leptos-shadcn-table = { workspace = true, optional = true }
leptos-shadcn-calendar = { workspace = true, optional = true }
leptos-shadcn-date-picker = { workspace = true, optional = true }
leptos-shadcn-pagination = { workspace = true, optional = true }
leptos-shadcn-slider = { workspace = true, optional = true }
leptos-shadcn-toggle = { workspace = true, optional = true }

# Advanced components (workspace dependencies)
leptos-shadcn-form = { workspace = true, optional = true }
leptos-shadcn-combobox = { workspace = true, optional = true }
leptos-shadcn-command = { workspace = true, optional = true }
leptos-shadcn-input-otp = { workspace = true, optional = true }
leptos-shadcn-breadcrumb = { workspace = true, optional = true }
leptos-shadcn-lazy-loading = { workspace = true, optional = true }
leptos-shadcn-error-boundary = { workspace = true, optional = true }
leptos-shadcn-registry = { workspace = true, optional = true }

# Additional dependencies
tailwind_fuse = "0.3"
lucide-leptos = "0.1"
gloo-timers = "0.3"

[features]
default = ["all-components"]
all-components = [
    "button", "input", "label", "checkbox", "switch", "radio-group", "select", "textarea",
    "card", "separator", "tabs", "accordion", "dialog", "popover", "tooltip",
    "alert", "badge", "skeleton", "progress", "toast", "table", "calendar", "date-picker", "pagination",
    "slider", "toggle",
    "form", "combobox", "command", "input-otp", "breadcrumb", "lazy-loading", "error-boundary", "registry"
]
button = ["leptos-shadcn-button"]
input = ["leptos-shadcn-input"]
label = ["leptos-shadcn-label"]
checkbox = ["leptos-shadcn-checkbox"]
switch = ["leptos-shadcn-switch"]
radio-group = ["leptos-shadcn-radio-group"]
select = ["leptos-shadcn-select"]
textarea = ["leptos-shadcn-textarea"]
card = ["leptos-shadcn-card"]
separator = ["leptos-shadcn-separator"]
tabs = ["leptos-shadcn-tabs"]
accordion = ["leptos-shadcn-accordion"]
dialog = ["leptos-shadcn-dialog"]
popover = ["leptos-shadcn-popover"]
tooltip = ["leptos-shadcn-tooltip"]
alert = ["leptos-shadcn-alert"]
badge = ["leptos-shadcn-badge"]
skeleton = ["leptos-shadcn-skeleton"]
progress = ["leptos-shadcn-progress"]
toast = ["leptos-shadcn-toast"]
table = ["leptos-shadcn-table"]
calendar = ["leptos-shadcn-calendar"]
date-picker = ["leptos-shadcn-date-picker"]
pagination = ["leptos-shadcn-pagination"]
slider = ["leptos-shadcn-slider"]
toggle = ["leptos-shadcn-toggle"]

# Advanced component features
form = ["leptos-shadcn-form"]
combobox = ["leptos-shadcn-combobox"]
command = ["leptos-shadcn-command"]
input-otp = ["leptos-shadcn-input-otp"]
breadcrumb = ["leptos-shadcn-breadcrumb"]
lazy-loading = ["leptos-shadcn-lazy-loading"]
error-boundary = ["leptos-shadcn-error-boundary"]
registry = ["leptos-shadcn-registry"]

[lib]
name = "leptos_shadcn_ui"
path = "src/lib.rs"
