[package]
name = "leptos-shadcn-pagination"
description = "Leptos port of shadcn/ui pagination"
homepage = "https://shadcn-ui.rustforweb.org/components/pagination.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
leptos.workspace = true
leptos-node-ref.workspace = true
leptos-struct-component.workspace = true
leptos-style.workspace = true
tailwind_fuse.workspace = true
web-sys.workspace = true
lucide-leptos = { workspace = true, features = ["navigation"] }
leptos-shadcn-button = { path = "../button" }

[features]
default = []
new_york = []

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }