[package]
name = "leptos-shadcn-visual-testing"
version = "0.8.1"
edition = "2021"
description = "Visual regression testing system for Leptos ShadCN UI components"

[dependencies]
leptos = "0.8.9"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4"
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]