[package]
name = "leptos-shadcn-signal-management"
version = "0.1.0"
edition = "2021"
authors = ["CloudShuttle <info@cloudshuttle.com>"]
license = "MIT"
repository = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
description = "Signal lifecycle management utilities for Leptos 0.8.8+ with tailwind-rs integration"

[dependencies]
leptos = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
js-sys = "0.3"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
leptos = { version = "0.8", features = ["csr"] }
wasm-bindgen-test = "0.3"
console_error_panic_hook = "0.1"
criterion = { version = "0.5", features = ["html_reports"] }
js-sys = "0.3"

[[bench]]
name = "signal_management_benchmarks"
harness = false
