[package]
name = "tailwind-rs-core-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for tailwind-rs-core"
homepage = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
repository = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
license = "MIT"
authors = ["CloudShuttle <info@cloudshuttle.com>"]
keywords = ["tailwind", "css", "rust", "web", "styling", "macros"]
categories = ["web-programming", "development-tools"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
