[package]
name = "leptos-shadcn-breadcrumb"
description = "Leptos port of shadcn/ui breadcrumb"
homepage = "https://shadcn-ui.rustforweb.org/components/breadcrumb.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.7.0"

[dependencies]
leptos = { workspace = true, features = ["csr", "ssr"] }
leptos-style = { workspace = true }
tailwind_fuse.workspace = true
serde = { version = "1.0", features = ["derive"] }
leptos-shadcn-signal-management = { path = "../../signal-management" }

[features]
default = ["leptos/csr"]
csr = ["leptos/csr"]
ssr = ["leptos/ssr"]
hydrate = ["leptos/hydrate"]
new_york = []

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }
