[package]
name = "leptos-shadcn-utils"
description = "Leptos port of shadcn/ui utils."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tailwind_fuse.workspace = true

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }
