[package]
name = "leptos-shadcn-error-boundary"
description = "Production-ready error boundary component for Leptos applications"
homepage = "https://shadcn-ui.rustforweb.org/components/error-boundary.html"

[dependencies]
leptos = { workspace = true, features = ["csr"] }
log = "0.4"
web-sys = { version = "0.3", features = ["Window", "Location"] }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
shadcn-ui-test-utils = { workspace = true }

[features]
default = []
development = []
production = []
