[package]
name = "leptos-shadcn-test-runner"
version = "0.8.1"
edition = "2021"
description = "Rust-based test runner and coverage measurement for Leptos ShadCN UI components"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["rlib"]

