[package]
name = "leptos-shadcn-api-standards"
version = "0.1.0"
edition = "2021"
description = "API standardization framework and validation tools for leptos-shadcn-ui"
repository = "https://github.com/cloud-shuttle/leptos-shadcn-ui"
license = "MIT"
authors = ["CloudShuttle <info@cloudshuttle.com>"]
keywords = ["leptos", "ui", "components", "standards", "validation"]
categories = ["web-programming", "gui", "development-tools"]

[dependencies]
# Core dependencies
leptos = { version = "0.8", features = ["csr", "hydrate"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

# Validation and testing
regex = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# CSS utilities
cssparser = "0.31"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.0"

[features]
default = ["validation", "linting"]
validation = []
linting = []
testing = []