[package]
name = "shadcn-registry"
description = "Rust port of shadcn registry."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.2.0"

[dependencies]
serde.workspace = true
serde_with = "3.10.0"
