[package]
name = "leptos-shadcn-form"
description = "Leptos port of shadcn/ui Form component"
homepage = "https://shadcn-ui.rustforweb.org/components/form.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version = "0.2.0"

[dependencies]
leptos.workspace = true
leptos-style = "0.2"
web-sys = { version = "0.3", features = ["HtmlFormElement", "HtmlInputElement", "HtmlElement", "Element", "Node", "Event", "EventTarget", "SubmitEvent"] }
wasm-bindgen = "0.2"
tailwind_fuse = "0.1"
leptos-shadcn-input = "0.2.0"
leptos-shadcn-button = "0.2.0"
gloo-timers = "0.3"
leptos-struct-component = "0.2"

[dev-dependencies]
shadcn-ui-test-utils = { path = "../../test-utils" }
wasm-bindgen-test = { workspace = true }

[lib]
name = "leptos_shadcn_form"
path = "src/lib.rs"

[[example]]
name = "form_example"
path = "examples/form_example.rs"
